name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs-10-0-x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10.0.x]
    steps:
      - name: Checkout SonataFlow repository
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-kie-kogito-docs
          ref: ${{ matrix.version }}
          path: sonataflow-docs

      - name: Build Sonataflow documentation
        run: |
          cd sonataflow-docs
          npm run install-build

      - name: Checkout Drools repository
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-kie-drools
          ref: ${{ matrix.version }}
          path: drools

      - name: Build Drools documentation
        run: |
          cd drools/drools-docs
          mvn -B clean install

      - name: Checkout Kogito documentation repository
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-kie-docs
          ref: ${{ matrix.version }}
          path: kogito-docs

      - name: Build Kogito documentation
        run: |
          cd kogito-docs
          mvn -B clean install -Dfull

      - name: Checkout Optaplanner repository
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-kie-optaplanner
          ref: ${{ matrix.version }}
          path: optaplanner

      - name: Build Optaplanner documentation
        run: |
          cd optaplanner/optaplanner-docs
          mvn -B clean install

      - name: Collect built docs
        run: |
          mkdir -p docs/${{ matrix.version }}/sonataflow
          cp -r sonataflow-docs/build/site/* docs/${{ matrix.version }}/sonataflow

          mkdir -p docs/${{ matrix.version }}/drools
          cp -r drools/drools-docs/target/website/docs/* docs/${{ matrix.version }}/drools

          mkdir -p docs/${{ matrix.version }}/kogito
          cp -r kogito-docs/doc-content/apache-kie-kogito/target/generated-docs/html_single/* docs/${{ matrix.version }}/kogito
          
          mkdir -p docs/${{ matrix.version }}/optaplanner
          cp -r optaplanner/optaplanner-docs/target/generated-docs/html_single/* docs/${{ matrix.version }}/optaplanner

      - name: Upload built docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}
          path: docs/${{ matrix.version }}

  build-docs-10-1-x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10.1.x]
    steps:
      - name: Checkout SonataFlow repository
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-kie-kogito-docs
          #ref: ${{ matrix.version }}
          ref: main
          path: sonataflow-docs

      - name: Build Sonataflow documentation
        run: |
          cd sonataflow-docs
          npm run install-build

      - name: Checkout kie-docs repository for Drools, Kogito, and OptaPlanner
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-kie-docs
          ref: ${{ matrix.version }}
          path: kie-docs

      - name: Build Drools, Kogito, and OptaPlanner documentation
        run: |
          cd kie-docs
          mvn -B clean install -Dfull

      - name: Collect built docs
        run: |
          mkdir -p docs/${{ matrix.version }}/sonataflow
          cp -r sonataflow-docs/build/site/* docs/${{ matrix.version }}/sonataflow

          mkdir -p docs/${{ matrix.version }}/drools
          cp -r kie-docs/drools-docs/target/website/docs/* docs/${{ matrix.version }}/drools

          mkdir -p docs/${{ matrix.version }}/kogito
          cp -r kie-docs/kogito-docs/doc-content/apache-kie-kogito/target/generated-docs/html_single/* docs/${{ matrix.version }}/kogito

          mkdir -p docs/${{ matrix.version }}/optaplanner
          cp -r kie-docs/optaplanner-docs/target/generated-docs/html_single/* docs/${{ matrix.version }}/optaplanner

      - name: Upload built docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}
          path: docs/${{ matrix.version }}

  deploy-website:
    runs-on: ubuntu-latest
    needs: [build-docs-10-0-x, build-docs-10-1-x]
    steps:
      - name: Checkout Apache KIE Website repository
        uses: actions/checkout@v4
        with:
          ref: main
          path: incubator-kie-website

      - name: Prepare docs folder
        run: mkdir -p docs

      - name: Download built docs artifacts
        uses: actions/download-artifact@v4
        with:
          path: docs

      - name: Copy docs to website static folder
        run: |
          for ver in $(ls docs); do
            echo "Processing version: $ver"
            mkdir -p incubator-kie-website/static/docs/$ver/sonataflow
            cp -r docs/$ver/sonataflow/* incubator-kie-website/static/docs/$ver/sonataflow

            mkdir -p incubator-kie-website/static/docs/$ver/drools
            cp -r docs/$ver/drools/* incubator-kie-website/static/docs/$ver/drools

            mkdir -p incubator-kie-website/static/docs/$ver/kogito
            cp -r docs/$ver/kogito/* incubator-kie-website/static/docs/$ver/kogito
          
            mkdir -p incubator-kie-website/static/docs/$ver/optaplanner
            cp -r docs/$ver/optaplanner/* incubator-kie-website/static/docs/$ver/optaplanner
          done

      - name: Build Apache KIE Website
        run: |
          cd incubator-kie-website
          npm install
          npm run build
          cp .asf.yaml build/.asf.yaml

      - name: Archive Apache KIE Website for preview
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: apache-kie-website
          path: incubator-kie-website/build
          overwrite: true

      - name: Deploy Apache KIE Website
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: incubator-kie-website/build
          publish_branch: deploy
